### PR TITLE
implement tunnel.isRoom

### PR DESCRIPTION
**Pull request by cryptix**
I was using this call for testing and i think it's good to have for local discovery connections, too.

### CODE REVIEW

**Comment by cryptix** [comment]
whops.. wrong indention

**Comment by staltz** [comment]
What happens when this is not implemented? With the approach I took in this module, I'm just testing the limits of muxrpc (cross language).

**Comment by cryptix** [comment]
Right now i'm getting `Error: method:tunnel,isRoom is not in list of allowed methods` and would (possibly should) import another secret-stack plugin to do my test call on.

**Comment by cryptix** [comment]
I also realized. The old version was promis-ified somehow.. my head hurts.

**Comment by cryptix** [comment]
Closing because @staltz and I decided to deprecate this. the original ssb-tunnel didnt have it and adding it to the `tunnel.*` namespace wasn't good. 

We will find a better place for it and my tests use a custom secret-stack plugin now.

**Pull request closed without merging**
